export const NEWS_FETCH_REQUESTED = 'NEWS_FETCH_REQUESTED';
export const NEWS_FETCH_SUCCEEDED = 'NEWS_FETCH_SUCCEEDED';
export const NEWS_FETCH_FAILED = 'NEWS_FETCH_FAILED';

export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';

export const USER_NEWS_FETCH_REQUESTED = 'USER_NEWS_FETCH_REQUESTED';
export const USER_NEWS_FETCH_SUCCEEDED = 'USER_NEWS_FETCH_SUCCEEDED';
export const USER_NEWS_FETCH_FAILED = 'USER_NEWS_FETCH_FAILED';
